### PR TITLE
fix Class 'Url' not found

### PR DESCRIPTION
**Pull request by DeeJaVu**

### CODE REVIEW

**Comment by thelfensdrfer** [comment]
Ahh sry got an error report a few hours ago and fixed it already. I think you raised the error? But thanks for your continuous work.

**Comment by DeeJaVu** [comment]
hmm strange i looked at the master branch before commiting

**Comment by thelfensdrfer** [comment]
Yeah but I didn't looked at the pull request before committing....sry

**Comment by DeeJaVu** [comment]
no problem

**Pull request closed without merging**
